### ISSUE TITLE
Data is not being updated on the fly

### ISSUE THREAD

**Issue by dylansproule** [manish-nepal/vue3-select-option-searchable#4]
For example a simple fetch after an initial init doesn't work.  If a Vue ref is used we cannot modify the binding, it just doesn't take, I've tried both composition and vue 3 setup as in your guide, so what if we don't have the data on time of render?

Thanks for any input!

**Comment by dylansproule** [comment]
Apparently this was the fix:

:key="componentKey"

incrementing the componentKey when data changes worked

**Comment by dylansproule** [comment]
Also the base data set needs to be at least 3 items, if only two:

vue3-select-option-search.js:115 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'title')
    at Proxy.<anonymous> (vue3-select-option-search.js:115:22)
    at renderComponentRoot (runtime-core.esm-bundler.js:816:16)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5701:46)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at instance.update (runtime-core.esm-bundler.js:5814:51)
    at setupRenderEffect (runtime-core.esm-bundler.js:5822:5)
    at mountComponent (runtime-core.esm-bundler.js:5612:5)
    at processComponent (runtime-core.esm-bundler.js:5565:9)
    at patch (runtime-core.esm-bundler.js:5040:11)
    at mountChildren (runtime-core.esm-bundler.js:5284:7)
