### ISSUE TITLE
Need at least three items as a base data set, which it shouldn't require

### ISSUE THREAD

**Issue by dylansproule** [manish-nepal/vue3-select-option-searchable#5]
An empty array should suffice for for not having errors.

The base data set needs to be at least 3 items from my testing, if only two:

vue3-select-option-search.js:115 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'title')
at Proxy. (vue3-select-option-search.js:115:22)
at renderComponentRoot (runtime-core.esm-bundler.js:816:16)
at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5701:46)
at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
at instance.update (runtime-core.esm-bundler.js:5814:51)
at setupRenderEffect (runtime-core.esm-bundler.js:5822:5)
at mountComponent (runtime-core.esm-bundler.js:5612:5)
at processComponent (runtime-core.esm-bundler.js:5565:9)
at patch (runtime-core.esm-bundler.js:5040:11)
at mountChildren (runtime-core.esm-bundler.js:5284:7)

**Comment by dylansproule** [comment]
For example, this works:

            titles: [
                { id: 0, title: 'Select Title' },
                { id: 0, title: 'Select Title' },
                { id: 0, title: 'Select Title' },
            ]
            
  If I remove one I receive the error.

**Comment by manish-nepal** [comment]
Thanks for pointing out, will let you know after fixing the issue.

**Comment by dylansproule** [comment]
Thank you!

**Comment by manish-nepal** [comment]
hello @dylansproule, i've fixed the empty array error and added loading indicator when array is empty,  please do update the package

**Comment by dylansproule** [comment]
Things are working great, thank you!
